AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for VPC'
Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '172.16.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: 'MyVpc'


#        
# {
#     "StackId": "arn:aws:cloudformation:us-west-2:174350032342:stack/vpc-stack/7b829f30-2b88-11f0-8e61-060a516a15d7"
# }