AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for VPC'
Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CiderBlock: '172.16.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        -Key: Name
        Value: 'MyVpc'